#ifndef __CONFIG_H
#define __CONFIG_H

#include <stdio.h>

#define SYSCLK_FREQUENCY_HZ 84000000
#define SYSTICK_FREQUENCY_HZ 1000
#define MICROSECONDS_PER_SECOND 1000000
#define PI 3.1415

#define MS_CALIBRACION_LINEA 2000
#define LECTURA_MAXIMO_SENSORES_LINEA 4096
#define LECTURA_MINIMO_SENSORES_LINEA 0

#define MILLIS_INICIO 3000

//#define MICROMETERS_PER_METER 1000000

#define CELL_DIMENSION 180
#define CELL_DIAGONAL 127.3
#define WALL_WIDTH 12
#define MIDDLE_MAZE_DISTANCE ((CELL_DIMENSION - WALL_WIDTH) / 2.)
#define SENSING_POINT_DISTANCE 0
#define WALL_LOSS_TO_SENSING_POINT_DISTANCE 106

#define ROBOT_FRONT_LENGTH 45
#define ROBOT_BACK_LENGTH 29
#define ROBOT_WIDTH 83
#define WHEELS_SEPARATION 73
#define ROBOT_MIDDLE_WIDTH ((ROBOT_WIDTH / 2.0))

#define MOTORES_MAX_PWM 1024

uint16_t get_start_millis(void);

#endif